name: KBO Lineup Crawler Bot

on:
  schedule:
    - cron: '*/15 4-13 * * *'
    - cron: '50 15 * * *'
  
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 💡 파이썬 버전을 3.11로 올려서 노란색 경고(FutureWarning) 완전 제거!
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin requests beautifulsoup4

      - name: Run Crawler Script
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: python crawler.py
